spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/admin
    username: admin
    password: password
  data:
    cassandra:
      keyspaceName: userdb
      contactPoints: localhost:9042
      local-datacenter: datacenter1
      # When running the application for the first time against a new Cassandra instance, this should be CREATE
      # More context on why this is the case can be found at this SO answer: https://stackoverflow.com/a/69203059
      # This bug is still there since 3.x versions :-(
      schemaAction: CREATE_IF_NOT_EXIST
  kafka:
    # Bootstrap-servers have to be a comma separated list of host:port combinations
    bootstrap-servers: localhost:9092
    template:
      default-topic: user-service-event
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      props: |
        key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
